debugging extra https fix

diff --git a/.github/workflows/web-api-tester.yaml b/.github/workflows/web-api-tester.yaml
--- a/.github/workflows/web-api-tester.yaml
+++ b/.github/workflows/web-api-tester.yaml
@@ -59,7 +59,7 @@ jobs:
       - name: Wait for the application to be ready
         run: |
           for i in {1..30}; do
-            response=$(curl -s -o /dev/null -w "%{http_code}" https://localhost:5001 || echo "connection_error")
+            response=$(curl -s -k -o /dev/null -w "%{http_code}" https://localhost:5001 || echo "connection_error")
             
             if [ "$response" -eq 200 ]; then
               echo "Application is ready! HTTP status code: $response"
